apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-demo
spec:
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause:
            duration: 10s
        - setWeight: 50
        - pause: { }
        - setWeight: 100