namePrefix: prod-
commonLabels:
  app: argo-demo
namespace: argo-demo-prod
commonAnnotations:
  note: prod
resources:
  - namespace.yaml
bases:
  - ../../base
patches:
  - replica_count.yaml
  - image.yaml
  - config.yaml