commonLabels:
  app: argo-demo
namespace: argo-demo-prod
commonAnnotations:
  note: production
resources:
  - namespace.yaml
bases:
  - ../../base
patches:
  - replica_count.yaml
  - config.yaml
  - deployment_strategy.yaml
patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: argo-demo
    path: image.yaml