apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-demo
spec:
  template:
    spec:
      containers:
        - name: argo-demo
          image: argo-demo:staging
          imagePullPolicy: IfNotPresent